/**
 * @tramo/github — official GitHub integration pack.
 *
 * Bundles webhook-trigger nodes (Issue / PR / Push events) and operation
 * nodes (issues, PRs, releases, files, dispatches) with stub executors.
 */

import { defineNodePack, defineStubExecutor } from '@tramo/runtime';
import type { IntegrationDefinition, NodeDefinition } from '@tramo/spec';

const COLOR = '#24292f';

const DEFINITION: IntegrationDefinition = {
  id: 'github',
  name: 'GitHub',
  description: 'Issues, PRs, releases, files, dispatches.',
  iconBrand: 'github',
  color: COLOR,
  category: 'Developer',
};

const NODES: NodeDefinition[] = [
  {
    id: 'webhook-trigger:github:issue',
    integrationId: 'github',
    name: 'GitHub · On Issue Event',
    operationName: 'On issue event',
    category: 'trigger',
    description: 'Fires when GitHub POSTs an issue webhook (opened, closed, edited, labelled, …).',
    icon: 'CloudDownload',
    iconBrand: 'github',
    color: COLOR,
    inputs: [],
    outputs: [{ key: 'out', label: 'Request', type: 'object' }],
    fields: [
      { key: 'path', type: 'text', label: 'Path', default: '/github/issues', help: 'Configure this URL in the repo\'s webhook settings.' },
      { key: 'method', type: 'select', label: 'Method', default: 'POST', options: [{ label: 'POST', value: 'POST' }] },
      { key: 'actions', type: 'text', label: 'Filter actions (comma-separated, blank = all)', default: 'opened,closed', optional: true },
      { key: 'secret', type: 'secret', label: 'Webhook secret', optional: true, help: 'GitHub signs payloads with X-Hub-Signature-256. Validation is a downstream step.' },
    ],
  },
  {
    id: 'webhook-trigger:github:pull-request',
    integrationId: 'github',
    name: 'GitHub · On Pull Request',
    operationName: 'On pull request',
    category: 'trigger',
    description: 'Fires on pull_request events (opened, ready_for_review, merged, …).',
    icon: 'CloudDownload',
    iconBrand: 'github',
    color: COLOR,
    inputs: [],
    outputs: [{ key: 'out', label: 'Request', type: 'object' }],
    fields: [
      { key: 'path', type: 'text', label: 'Path', default: '/github/pulls' },
      { key: 'method', type: 'select', label: 'Method', default: 'POST', options: [{ label: 'POST', value: 'POST' }] },
      { key: 'actions', type: 'text', label: 'Filter actions', default: 'opened,closed,ready_for_review', optional: true },
      { key: 'secret', type: 'secret', label: 'Webhook secret', optional: true },
    ],
  },
  {
    id: 'webhook-trigger:github:push',
    integrationId: 'github',
    name: 'GitHub · On Push',
    operationName: 'On push',
    category: 'trigger',
    description: 'Fires when GitHub POSTs a push webhook for any branch.',
    icon: 'CloudDownload',
    iconBrand: 'github',
    color: COLOR,
    inputs: [],
    outputs: [{ key: 'out', label: 'Request', type: 'object' }],
    fields: [
      { key: 'path', type: 'text', label: 'Path', default: '/github/push' },
      { key: 'method', type: 'select', label: 'Method', default: 'POST', options: [{ label: 'POST', value: 'POST' }] },
      { key: 'branchFilter', type: 'text', label: 'Branch filter (regex, blank = all)', default: '^refs/heads/main$', optional: true },
      { key: 'secret', type: 'secret', label: 'Webhook secret', optional: true },
    ],
  },
  {
    id: 'github-issue-create',
    integrationId: 'github',
    name: 'GitHub · Create Issue',
    operationName: 'Create issue',
    category: 'action',
    description: 'Open a new issue in a repository.',
    icon: 'Cable',
    iconBrand: 'github',
    color: COLOR,
    inputs: [{ key: 'in', label: 'Input', type: 'any' }],
    outputs: [{ key: 'out', label: 'Issue', type: 'object' }],
    fields: [
      { key: 'repo', type: 'text', label: 'owner/repo', default: 'octocat/hello-world' },
      { key: 'title', type: 'text', label: 'Title (supports {{var}})', default: 'Triggered from tramo' },
      { key: 'body', type: 'textarea', label: 'Body', default: '', optional: true },
      { key: 'labels', type: 'text', label: 'Labels (comma-separated)', default: '', optional: true },
      { key: 'assignees', type: 'text', label: 'Assignees (comma-separated)', default: '', optional: true },
      { key: 'token', type: 'secret', label: 'GitHub token', optional: true },
    ],
  },
  {
    id: 'github-issue-comment',
    integrationId: 'github',
    name: 'GitHub · Comment on Issue',
    operationName: 'Comment on issue',
    category: 'action',
    description: 'Post a comment on an existing issue or pull request.',
    icon: 'Cable',
    iconBrand: 'github',
    color: COLOR,
    inputs: [{ key: 'in', label: 'Input', type: 'any' }],
    outputs: [{ key: 'out', label: 'Comment', type: 'object' }],
    fields: [
      { key: 'repo', type: 'text', label: 'owner/repo', default: 'octocat/hello-world' },
      { key: 'issueNumber', type: 'number', label: 'Issue or PR number', default: 1 },
      { key: 'body', type: 'textarea', label: 'Comment (supports {{var}})', default: '' },
      { key: 'token', type: 'secret', label: 'GitHub token', optional: true },
    ],
  },
  {
    id: 'github-issue-close',
    integrationId: 'github',
    name: 'GitHub · Close Issue',
    operationName: 'Close issue',
    category: 'action',
    description: 'Close an issue with an optional reason (completed / not planned).',
    icon: 'Cable',
    iconBrand: 'github',
    color: COLOR,
    inputs: [{ key: 'in', label: 'Input', type: 'any' }],
    outputs: [{ key: 'out', label: 'Issue', type: 'object' }],
    fields: [
      { key: 'repo', type: 'text', label: 'owner/repo', default: 'octocat/hello-world' },
      { key: 'issueNumber', type: 'number', label: 'Issue number', default: 1 },
      {
        key: 'reason',
        type: 'select',
        label: 'State reason',
        default: 'completed',
        options: [
          { label: 'Completed', value: 'completed' },
          { label: 'Not planned', value: 'not_planned' },
          { label: 'Reopened', value: 'reopened' },
        ],
      },
      { key: 'token', type: 'secret', label: 'GitHub token', optional: true },
    ],
  },
  {
    id: 'github-pr-create',
    integrationId: 'github',
    name: 'GitHub · Open Pull Request',
    operationName: 'Open pull request',
    category: 'action',
    description: 'Open a pull request between two branches.',
    icon: 'Cable',
    iconBrand: 'github',
    color: COLOR,
    inputs: [{ key: 'in', label: 'Input', type: 'any' }],
    outputs: [{ key: 'out', label: 'PR', type: 'object' }],
    fields: [
      { key: 'repo', type: 'text', label: 'owner/repo', default: 'octocat/hello-world' },
      { key: 'title', type: 'text', label: 'Title', default: 'New PR from tramo' },
      { key: 'head', type: 'text', label: 'Head branch', default: 'feature/x' },
      { key: 'base', type: 'text', label: 'Base branch', default: 'main' },
      { key: 'body', type: 'textarea', label: 'Body', default: '', optional: true },
      { key: 'draft', type: 'boolean', label: 'Draft', default: false, optional: true },
      { key: 'token', type: 'secret', label: 'GitHub token', optional: true },
    ],
  },
  {
    id: 'github-repo-star',
    integrationId: 'github',
    name: 'GitHub · Star Repo',
    operationName: 'Star repository',
    category: 'action',
    description: 'Star a repository with the authenticated user.',
    icon: 'Cable',
    iconBrand: 'github',
    color: COLOR,
    inputs: [{ key: 'in', label: 'Input', type: 'any' }],
    outputs: [{ key: 'out', label: 'Result', type: 'object' }],
    fields: [
      { key: 'repo', type: 'text', label: 'owner/repo', default: 'octocat/hello-world' },
      { key: 'token', type: 'secret', label: 'GitHub token', optional: true },
    ],
  },
  {
    id: 'github-dispatch',
    integrationId: 'github',
    name: 'GitHub · Trigger Workflow',
    operationName: 'Dispatch workflow',
    category: 'action',
    description: 'Trigger a repository_dispatch event for GitHub Actions.',
    icon: 'Cable',
    iconBrand: 'github',
    color: COLOR,
    inputs: [{ key: 'in', label: 'Input', type: 'any' }],
    outputs: [{ key: 'out', label: 'Result', type: 'object' }],
    fields: [
      { key: 'repo', type: 'text', label: 'owner/repo', default: 'octocat/hello-world' },
      { key: 'eventType', type: 'text', label: 'Event type', default: 'tramo-run' },
      { key: 'payload', type: 'json', label: 'Client payload (JSON)', default: '{}', optional: true },
      { key: 'token', type: 'secret', label: 'GitHub token', optional: true },
    ],
  },
  {
    id: 'github-release-create',
    integrationId: 'github',
    name: 'GitHub · Create Release',
    operationName: 'Create release',
    category: 'action',
    description: 'Cut a release from a tag with optional release notes.',
    icon: 'Cable',
    iconBrand: 'github',
    color: COLOR,
    inputs: [{ key: 'in', label: 'Input', type: 'any' }],
    outputs: [{ key: 'out', label: 'Release', type: 'object' }],
    fields: [
      { key: 'repo', type: 'text', label: 'owner/repo', default: 'octocat/hello-world' },
      { key: 'tagName', type: 'text', label: 'Tag (e.g. v1.0.0)', default: 'v0.1.0' },
      { key: 'name', type: 'text', label: 'Release name', default: '', optional: true },
      { key: 'body', type: 'textarea', label: 'Release notes (supports {{var}})', default: '', optional: true },
      { key: 'draft', type: 'boolean', label: 'Draft', default: false, optional: true },
      { key: 'prerelease', type: 'boolean', label: 'Pre-release', default: false, optional: true },
      { key: 'token', type: 'secret', label: 'GitHub token', optional: true },
    ],
  },
  {
    id: 'github-file-get',
    integrationId: 'github',
    name: 'GitHub · Get File Contents',
    operationName: 'Get file contents',
    category: 'action',
    description: 'Fetch a file from a repository at a given path and ref.',
    icon: 'Cable',
    iconBrand: 'github',
    color: COLOR,
    inputs: [{ key: 'in', label: 'Input', type: 'any' }],
    outputs: [
      { key: 'out', label: 'File', type: 'object' },
      { key: 'error', label: 'Error', type: 'object' },
    ],
    fields: [
      { key: 'repo', type: 'text', label: 'owner/repo', default: 'octocat/hello-world' },
      { key: 'path', type: 'text', label: 'File path', default: 'README.md' },
      { key: 'ref', type: 'text', label: 'Branch / tag / SHA', default: 'main', optional: true },
      { key: 'token', type: 'secret', label: 'GitHub token', optional: true },
    ],
  },
];

export default defineNodePack({
  id: 'github',
  name: 'GitHub',
  version: '0.1.0',
  entries: NODES.map((definition) => ({
    definition,
    executor: defineStubExecutor(definition),
  })),
  integrations: [DEFINITION],
});
