/**
 * Core types for tramo — the workflow-document-of-truth model.
 *
 * Same design principle as htmlstudio's HTML-source-of-truth: one
 * canonical representation (here, WorkflowDoc), mutated by a small
 * union of typed Patches. Humans click in the UI, LLMs emit the
 * same patches via a tool call. One channel, two callers.
 */

/* ====================================================================== */
/* Document                                                                 */
/* ====================================================================== */

export interface WorkflowDoc {
  /** Schema version. Bumped only on breaking changes. */
  version: 1;
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  meta: WorkflowMeta;
}

export interface WorkflowMeta {
  name?: string;
  description?: string;
  /** Free-form tags for filtering. */
  tags?: string[];
  /** Last-touched timestamp (ms since epoch). Optional; runtimes/UI may stamp it. */
  updatedAt?: number;
}

export interface WorkflowNode {
  /** Stable id, generated by `newNodeId()`. Survives the lifetime of the node. */
  id: string;
  /** References a NodeDefinition.id from the registry. */
  type: string;
  /** Position on the canvas (XYFlow coordinate space). */
  position: { x: number; y: number };
  /** Typed against the matching NodeDefinition.fields. */
  config: Record<string, unknown>;
  /** Optional display label override; defaults to NodeDefinition.name. */
  label?: string;
}

export interface WorkflowEdge {
  id: string;
  source: string;
  target: string;
  /** Output port key on `source`. Defaults to 'out' if unspecified. */
  sourceHandle?: string;
  /** Input port key on `target`. Defaults to 'in' if unspecified. */
  targetHandle?: string;
}

/* ====================================================================== */
/* Patches                                                                  */
/* ====================================================================== */

/**
 * Seven patch kinds — the only ways to mutate a WorkflowDoc.
 *
 * Mirrors htmlstudio's Patch union in spirit: narrow patches (move-node,
 * update-node-config) for surgical edits, broader patches (set-full-doc)
 * for whole-document replacement (e.g. an LLM regeneration).
 */
export type Patch =
  | { kind: 'add-node'; node: WorkflowNode }
  | { kind: 'update-node-config'; id: string; config: Record<string, unknown>; replace?: boolean }
  | { kind: 'move-node'; id: string; position: { x: number; y: number } }
  | { kind: 'remove-node'; id: string }
  | { kind: 'add-edge'; edge: WorkflowEdge }
  | { kind: 'remove-edge'; id: string }
  | { kind: 'set-full-doc'; doc: WorkflowDoc };

export interface PatchResult {
  ok: boolean;
  doc: WorkflowDoc;
  error?: string;
}

/* ====================================================================== */
/* Node definitions (editor-side metadata)                                  */
/* ====================================================================== */

export type PortType =
  | 'any'
  | 'string'
  | 'number'
  | 'boolean'
  | 'object'
  | 'array';

export interface NodePort {
  /** Stable key used in edges' sourceHandle/targetHandle. */
  key: string;
  /** Human-readable label shown in the inspector. */
  label: string;
  /** Hint for the runtime + UI — no hard schema enforcement at v0.1. */
  type: PortType;
  description?: string;
}

export type NodeFieldType =
  | 'text'
  | 'textarea'
  | 'url'
  | 'number'
  | 'boolean'
  | 'select'
  | 'json'
  | 'code'
  | 'secret';

export interface NodeFieldOption {
  label: string;
  value: string;
}

export interface NodeField {
  /** Key used in the node's `config` object. */
  key: string;
  type: NodeFieldType;
  label: string;
  help?: string;
  default?: string | number | boolean | null;
  options?: NodeFieldOption[];
  /** Allow empty/null. Default false. */
  optional?: boolean;
  /** For 'code' fields, the language (e.g. 'javascript', 'sql'). */
  language?: string;
}

export type NodeCategory =
  | 'trigger'
  | 'action'
  | 'transform'
  | 'logic'
  | 'ai'
  | 'io';

export interface NodeDefinition {
  /** Stable id used by WorkflowNode.type and by the runtime's executor map. */
  id: string;
  name: string;
  category: NodeCategory;
  description: string;
  /** Phosphor icon name or emoji glyph for palette / canvas cards. */
  icon: string;
  /** Input ports (empty for triggers). */
  inputs: NodePort[];
  /** Output ports. */
  outputs: NodePort[];
  /** Editable fields rendered in the inspector. */
  fields: NodeField[];
  /** Accent color (hex) — used on the canvas node's left border. Optional. */
  color?: string;
}
